export const SET_CUSTOMER = "SET_CUSTOMER";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST";
export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_ADRESS_REQUEST = "EDIT_ADRESS_REQUEST";
export const EDIT_PROFILE_PASS_REQUEST = "EDIT_PROFILE_PASS_REQUEST";
export const CHECK_AUTH = "CHECK_AUTH";

export const SET_POPUP_VALIDATOR = "SET_POPUP_VALIDATOR";
export const CLEAR_POPUP_VALIDATOR = "CLEAR_POPUP_VALIDATOR";

export const GET_SLIDES = "GET_SLIDES";

export const GET_PRODUCTS_MENU = "GET_PRODUCTS_MENU";
export const WAIT_PRODUCTS_MENU = "WAIT_PRODUCTS_MENU";

export const GET_PRODUCTS_FILTERS = "GET_PRODUCTS_FILTERS";
export const WAIT_PRODUCTS_FILTERS = "WAIT_PRODUCTS_FILTERS";

export const GET_RECOMMENDED_PRODUCTS = "GET_RECOMMENDED_PRODUCTS";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_FILTRED_PRODUCTS = "GET_FILTRED_PRODUCTS";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";

export const COUNT_OF_CART = "COUNT_OF_CART";
export const GET_PRODUCT_IN_CART = "GET_PRODUCT_IN_CART";

export const FETCH_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const FETCH_BLOG_FAILURE = "GET_BLOG_FAILURE";

export const FETCH_BLOG_DETAILS_REQUEST = "GET_BLOG_DETAILS_REQUEST";
export const FETCH_BLOG_DETAILS_SUCCESS = "GET_BLOG_DETAILS_SUCCESS";
export const FETCH_BLOG_DETAILS_FAILURE = "GET_BLOG_DETAILS_FAILURE";

export const SET_ORDER = "SET_ORDER";
export const GET_ORDERS = "GET_ORDERS";

export const SET_STARS = "SET_STARS";

export const ADD_SUBSCRIBER = "ADD_SUBSCRIBER";
export const ADD_SUBSCRIBER_ERROR = "ADD_SUBSCRIBER_ERROR";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const IS_LOADING_SUBSCRIBER = "IS_LOADING_SUBSCRIBER";
